// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfadhnvLshClpqO6Ry8ZD5iuf2HUDrN4U',
    appId: '1:627756843136:web:7e9be3b98b00f7edc0a665',
    messagingSenderId: '627756843136',
    projectId: 'projectrpl-b5a36',
    authDomain: 'projectrpl-b5a36.firebaseapp.com',
    databaseURL: 'https://projectrpl-b5a36-default-rtdb.firebaseio.com',
    storageBucket: 'projectrpl-b5a36.appspot.com',
    measurementId: 'G-Y9P5HR8RWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphPuxHQQDUeS47wC532rm7A78t9rbu9g',
    appId: '1:627756843136:android:453d91d06e74c45ac0a665',
    messagingSenderId: '627756843136',
    projectId: 'projectrpl-b5a36',
    databaseURL: 'https://projectrpl-b5a36-default-rtdb.firebaseio.com',
    storageBucket: 'projectrpl-b5a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYzL923oclcApo24QZq_fCwdN6cIaPFk',
    appId: '1:627756843136:ios:00270894b0ef6b77c0a665',
    messagingSenderId: '627756843136',
    projectId: 'projectrpl-b5a36',
    databaseURL: 'https://projectrpl-b5a36-default-rtdb.firebaseio.com',
    storageBucket: 'projectrpl-b5a36.appspot.com',
    iosBundleId: 'com.example.bontable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYzL923oclcApo24QZq_fCwdN6cIaPFk',
    appId: '1:627756843136:ios:00270894b0ef6b77c0a665',
    messagingSenderId: '627756843136',
    projectId: 'projectrpl-b5a36',
    databaseURL: 'https://projectrpl-b5a36-default-rtdb.firebaseio.com',
    storageBucket: 'projectrpl-b5a36.appspot.com',
    iosBundleId: 'com.example.bontable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfadhnvLshClpqO6Ry8ZD5iuf2HUDrN4U',
    appId: '1:627756843136:web:488014c65d591823c0a665',
    messagingSenderId: '627756843136',
    projectId: 'projectrpl-b5a36',
    authDomain: 'projectrpl-b5a36.firebaseapp.com',
    databaseURL: 'https://projectrpl-b5a36-default-rtdb.firebaseio.com',
    storageBucket: 'projectrpl-b5a36.appspot.com',
    measurementId: 'G-MXD1KV8BSK',
  );
}
